ipaserver_domain: treadansible.com
ipaserver_realm: TREADANSIBLE.COM
ipaserver_admin_password: 'abcd1234'
ipaserver_ds_password: 'abcd1234'
ipaserver_ip: 192.168.1.130
ipaserver_setup_dns: true
ipaserver_auto_forwarders: true
ipaserver_no_dnssec_validation: true
ipadm_password: 'abcd1234'
ipaadmin_password: 'abcd1234'
nfs_export_dir: /home
nfs_server_ip: 192.168.1.130
