---
- name: Install NFS Server Tools
  ansible.builtin.package:
    name: "{{ nfs_server_package }}"
    state: present
  loop: "{{ nfs_server_packages }}"
  loop_control:
    loop_var: nfs_server_package
    label: "Installing {{ nfs_server_package }} package."

- name: Set sebool
  ansible.builtin.command:
    cmd: "setsebool -P use_nfs_home_dirs on"

- name: Start and enable NFS services
  ansible.builtin.service:
    name: "{{ nfs.name }}"
    state: "{{ nfs.state }}"
    enabled: "{{ nfs.enabled }}"
  loop: "{{ nfs_server_services }}"
  loop_control:
    loop_var: nfs
    label: "Starting and enabling {{ nfs.name }} service."

- name: Configure /etc/exports dynamically
  ansible.builtin.template:
    src: exports.j2
    dest: "{{ nfs_server_config_file }}"
  notify: Export file

- name: Enable dynamic automounting
  ansible.builtin.template:
    src: auto.master.j2
    dest: /etc/auto.master
  notify: Restart autofs service

- name: Allow nfs related services through firewall
  ansible.posix.firewalld:
    service: "{{ nfs_server_firewall_service }}"
    state: enabled
    permanent: true
    immediate: true
  loop: "{{ nfs_server_firewall_services }}"
  loop_control:
    loop_var: nfs_server_firewall_service
    label: "Adding {{ nfs_server_firewall_service }} service to firewall."

- name: Ensure in /etc/idmapd.conf 'Domain = treadansible.com'
  ansible.builtin.lineinfile:
    path: /etc/idmapd.conf
    regexp: '^#Domain ='
    line: Domain = treadansible.com