---
- name: Deploy IPA Server 
  ansible.builtin.import_playbook: install-server.yml

- name: Enroll FreeIPA Clients
  ansible.builtin.import_playbook: install-client.yml

- name: Configure NFS Server
  hosts: nfsserver
  become: true
  roles:
    - nfs_server

- name: Create FreeIPA Users
  ansible.builtin.import_playbook: create_users.yml
    
