ipaclients:
  hosts:
    ipaclient1:
      ansible_host: ipaclient1.ansible.com
    ipaclient2:
      ansible_host: ipaclient2.ansible.com
    ipaclient3:
      ansible_host: ipaclient3.ansible.com

ipaserver:
  hosts:
    ldapsvr:
      ansible_host: ldpsvr.ansible.com

nfsserver:
  hosts:
    nfs_svr:
      ansible_host: ldpsvr.ansible.com

lab:
  children:
    ipaserver:
    ipaclients:
