ipaclients:
  hosts:
    ipaclient1:
      ansible_host: ipaclient1.treadansible.com
    ipaclient2:
      ansible_host: ipaclient2.treadansible.com
    ipaclient3:
      ansible_host: ipaclient3.treadansible.com

ipaserver:
  hosts:
    ldapsvr:
      ansible_host: ldapsvr.treadansible.com

nfsserver:
  hosts:
    ldapsvr:

lab:
  children:
    ipaserver:
    ipaclients:
    nfsserver:
